-- Base schema for audit_event. Without this, a brand-new PostgreSQL database has no path to
-- obtain the table at all: ddl-auto=none means Hibernate never creates it, and (before this
-- file existed) the only other script touching audit_event was an ALTER TABLE that assumed the
-- table already existed - which would fail startup outright against a genuinely fresh database.
-- This idempotent CREATE TABLE IF NOT EXISTS closes that gap using the same lightweight
-- spring.sql.init mechanism the chain-lock table already relies on (no Flyway/Liquibase, no new
-- dependency). It includes archived/archived_at directly, so a fresh database gets the full
-- Scenario A + B shape in one step; if audit_event already exists (e.g. from before Scenario B),
-- this statement is a no-op and audit-event-scenario-b-schema.sql is what adds those two columns
-- to it instead. Never drops or recreates the table, and never runs if it already exists.
CREATE TABLE IF NOT EXISTS audit_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type VARCHAR(255) NOT NULL,
    actor_id VARCHAR(255) NOT NULL,
    resource_type VARCHAR(255) NOT NULL,
    resource_id VARCHAR(255) NOT NULL,
    payload TEXT NOT NULL,
    timestamp TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    sequence_number BIGINT NOT NULL,
    previous_hash VARCHAR(255) NOT NULL,
    event_hash VARCHAR(255) NOT NULL,
    archived BOOLEAN NOT NULL DEFAULT FALSE,
    archived_at TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT uk_audit_event_sequence_number UNIQUE (sequence_number)
);
